### ISSUE TITLE
The ukbschemas_db function generates a parsing failure

### ISSUE THREAD

**Issue by Feakster** [bjcairns/ukbschemas#28]
Upon executing the following code a parsing failure is produced:
```r
db <- ukbschemas_db(path = tempdir(), overwrite = T)
```
The parsing failure reads:
```text
Warning: 1 parsing failure.
row col  expected    actual                                                            file
 84  -- 6 columns 9 columns 'http://biobank.ndph.ox.ac.uk/showcase/scdown.cgi?fmt=txt&id=4'
```

**Comment by Feakster** [comment]
I had forked this hoping to fix the problem, but there doesn't appear to be anything that can be done your end. The problem lies in the _"returns.txt"_ file, downloaded from: http://biobank.ndph.ox.ac.uk/showcase/scdown.cgi?fmt=txt&id=4. Line 85 of this file is malformed, containing an embedded itemised list. The list is itemised using numbers, followed by a full stop and a tab:

```text
1641	4844	A Genome-Wide Association Study Finds Genetic Associations with Broadly-Defined Headache in UK Biobank (N = 223,773)	0	0	1.	Headache as a single entity, is mainly driven by neuron changes, not by vascular changes. <BR>  2.	Headache and other psychological traits (such as neuroticism, depression, etc) share common genetic components.   <BR>  3.	Our GWAS confirmed 14 previously reported loci for migraine and identified 14 new loci for headache as a single entity.  <BR>
```

The field containing this list should have been quoted by UKB to allow it to be more easily parsed, but this has not been done. The problem needs to be reported upstream.

**Comment by bjcairns** [comment]
This problem is, as you've seen, with unsanitised field contents (tabs in field in what should be a tab-separated file). It has been reported back to UKB, but not fixed yet.
